### ISSUE TITLE
Auth MVP

### ISSUE THREAD

**Issue by dorotaaa** [dorotaaa/posergram#3]
## [Auth MVP]

- [ ] MVP is completely styled and seeded
- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + shift + R)
- [x] MVP handles errors with informative messages for user

**Comment by jliversi** [comment]
- [ ] Add a footer (like the one on the real instagram) but instead of all the links on real instagram, have it contain links to your github/linkedin/personal site.
